### ISSUE TITLE
[BUG] : [Staging 22.11.2019] Materialist need for Megastructure not satisfied by repairing ruined Megastructures

### ISSUE THREAD

**Issue by Vstef** [Stellaris-Immortal/retile#128]
Materialists are not satisfied by the repaired Mega Art Installation. I assume that's the case for a repaired Science Nexus as well. Additionally, the faction file says you need the techs for either of them in order to qualify, but what if you just repair one (and thus don't need the tech)?

**Comment by doctorsandwich** [comment]
Other faction demand stuff:
The demand XENOPHOBE_CLOSED_BORDERS asks for {has_policy_flag = first_contact_attack_allowed} instead of closed borders
The demand MATERIALIST_PRECURSOR_SECRETS is correct in vanilla, here it doesn't cover all cases.
The demand AUTHORITARIAN_HEALTHCARE_CAMPAIGN says they hate healthcare campaigns, but owner = { has_edict = healthcare_campaign } means they hate not having healthcare campaigns
The demand SPIRITUALIST_RELIC has potential host_has_dlc = "Ancient Relics Story Pack" but players can get relics without the dlc
The demand SPIRITUALIST_CHEMICAL_BLISS might have colors switched, not sure about this one.

**Comment by doctorsandwich** [comment]
Xenophobes both want and hate population control (XENOPHOBE_POP_CONTROLS and XENOPHOBE_NO_POP_CONTROLS )

**Comment by Metadig** [comment]
All of these should be correct in the next update.
