### ISSUE TITLE
[SUGGESTION] : Planetary Pollution Levels

### ISSUE THREAD

**Issue by AstralVoid** [Stellaris-Immortal/retile#181]
Planetary pollution seems to be something that, once you have a big enough planet, has a runaway effect without putting a lot of additional work into anti-pollution measures that cause problems with the limited amount of pops available currently. 

Some random ideas/suggestions I was considering when interacting with the mechanic (especially after having to build maintenance complexes on all of my planets late game):

1) **Ring worlds should have a large decrease to pollution baseline (something like -500 or -1000, not sure on exact numbers)**
_These are created structures engineered to perfection and a huge investment - why wouldn't they have a shiny Trash-o-matic 9000 on every corner? It could still be overrun if poorly managed or intentionally mismanaged, but it's much less easy to do, and requires less in the way of pop micromanagement to combat._
2) **Tomb Worlds should not be affected by pollution by way of events, but also shouldn't receive benefits or detriments for habitability/growth/etc.**
_It's possible they already aren't impacted by events like Arcologies, but who cares that the irradiated hellhole of a planet is glowing a little greener than usual? It's not like there's a biosphere to disrupt at this point. Is it possible to set pollution at a flat 0 value regardless of other circumstances? I also noted that the tomb world start ends up with less than 100% habitability to begin; submitted as a separate bug report._
3) **Gaia worlds should, by contrast, be more affected by pollution than normal, encouraging careful management**
_They already give some pretty hefty bonuses that make up for the fact that you have to dedicate some pops to being custodians. They are an engineered world, unlike a ring world segment, and still have a biosphere to maintain._
4) **Ecumenopolis worlds need better pollution management tools, possibly at a decision level**
_They aren't affected by events as far as I can tell, but are still pretty heavily impacted by the pollution on a stability standpoint. The slower pop growth in Immortal hurts them for longer, given the large number of slots to fill. Maybe a (reversible) decision to lose that +20% job bonus, but also reduce pollution from jobs as well?_

Bonus: **Make the Trium Atmospheric Deodorizer Deployment from the Caravaneers reduce pollution by some amount rather than the current meager immigration pull/growth bonus.**
_This thing actually has a function now! It does specifically note that they are atmospheric scrubbers of some kind in the flavor text._ 

Bonus2: **Starbase modules that can be built around black holes, that give a small (-10?) empire-wide bonus to pollution?**
_If the resident Ancient Caretakers can use a black hole as a disposal platform, why can't we?_

**Comment by Metadig** [comment]
1. Artificial environments have to be managed by the empire instead of left to nature. That means you're going to have to construct that infrastructure. It's an intentional design that natural environments are more pollution resistant.

That being said, the Galactic Wonders AP is going to add a modifier to Ringworlds that reduce their base pollution by -300 (a fully upgraded and staffed maintenance depot). Hopefully this will help them feel less punishing if you dedicate yourself to it.

2. They are going to be more polluted overall with the associated penalties (they're hard to live on after all), but as part of their trade-off they won't get many pollution events (like climate change). Tomb World habitability might be modified to make your pops more pollution resistant to make that an interesting choice.

3. Gaia specific deposits actually give more pollution reduction than normal, but the blockers that appear on natural Gaia worlds produce biodiversity loss and habitat loss blockers when removed, making them more of an investment. They're already worse options than city worlds, so I'm hesitant to make them more vulnerable and I want them to be thematically distinct from artificial structures which are vulnerable to pollution due to their lack of a natural environment. If you have any suggestions feel free to share them.

4. The new overhaul to deposits should really help you manage pollution better. The plan with the ecumenopolis is that is has a massive immigration bonus, so it requires other worlds to feed pops from. In general, your city woulds should require a lot of other outside resources to build up and maintain.

Bonus: That's a good idea.

Bonus2: This was a common kind of suggestion for Ecology Mod. Though it's a nice idea, it does mean losing your materials. I'd rather focus waste management around the theme of a metabolism, where materials change form or are reused. This is also inefficient because you can just throw materials into stars anyway if you want to dispose of them - you don't need a black hole for that. If I were to add this, it would be a policy, and it would come with some cost (like custodian production -100%).

**Comment by gebnar** [comment]
Pollution has changed quite a lot since this issue was posted. We've been getting much more positive feedback about the current systems. I'm going to close the issue, but if you feel it's still a concern in your games, please re-open it for further discussion!
