### ISSUE TITLE
[SUGGESTION] : Robot Overhaul for Organics

### ISSUE THREAD

**Issue by Vstef** [Stellaris-Immortal/retile#23]
One of the issues I find in vanilla is that it is always advantageous, even for Spiritualists, to construct Robot Assembly Plants as pop growth is king. I propose rectifying this by modifying the Mechanist civic to add Robot Output instead of another Replicator. Replicator base assembly rate increased to 3. Trait which increases assembly rate removed. Policy which controls robot construction should be modified to instead add 100% additive pop growth if Robots are outlawed, equal to the assembly rate of robots. 

Thus Robots would be a choice if you wanted to get Habitability independent pops and not an automatic choice for extra pop growth. This would also be a powerful buff for Psionics who lack the pop growth of the other two Ascensions. Synth Ascension should still give another Replicator job as it does now, for a total of 6 base assembly rate. Perhaps another 17% should be added to it or Flesh is Weak for a total of 9 assembly rate, which is still slightly lower than what Bio pops can achieve on Ecus, even without Bio Ascension's Fertile trait. 

If you picked Synth Ascension then organics cannot grow anymore on your planets and you either have to assimilate them as Synths or purge them. Cybrex Relic should be balanced around this, as the Assembly Rate active would be too strong for Synth Ascension. It should give 10% Robot Output or something of the sort.

**Comment by gebnar** [comment]
We're going to be ovehauling the ethics wheel eventually, and separating robots from the ethics somewhat. Sci-fi culture has a rich history of spiritualist robots, so we think the current system is quite limiting of RP.

**Comment by Vstef** [comment]
Spiritualist Robots should be a civic, then. I see that being done in the Cultural Overhaul mod as the Machine Cult civic.

**Comment by gebnar** [comment]
We're probably going to remove the religion/robots dichotomy from the game altogether. Until then, we'll just be issuing band-aid fixes for the most egregious of the issues related to it.

Mechanist, for instance, has been severely nerfed from vanilla. They only ever get the 1 extra assembly job, and any empire that completes synth ascension also gets that assembly job (doesn't stack). I think they're not too far off balance from the other origin-type civics right now. But I'm leaving the issue open - for discussion, and because it *is* an issue!

**Comment by gebnar** [comment]
Closing this for now. We'll do a big balance pass sometime after we hit Beta.
